### ISSUE TITLE
build fails with dx merger error

### ISSUE THREAD

**Issue by raoulney** [Calsign/APDE#11]
After installing APDE on an Android 4.4.2 device I am unable to build any of the examples.  
I have previously installed and run successfully on an older 4.1.1 device.

All attempts to build&run give the same error from the DX Merger as below.  There is 1gb available on the internal storage.

verbose output from a build attempt immediately after installation:
=============================================

Initializing build sequence...
Target: debug
Deleted old build folder
Pre-processing...
Injected log broadcaster
Writing AndroidManifest.xml...
Writing resources...
Copying android.jar...
Copying Processing libraries...
Copying dexed Processing libraries...
Copying contributed libaries...
Detected architecture armeabi-v7a
Using position independent executable (PIE) AAPT binary
Copying AAPT...
Changing execution permissions for AAPT...
Copying GLSL shader files...

Packaging resources with AAPT...
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
Compiling with ECJ...
Compiling: /data/data/com.calsignlabs.apde/app_build/src/processing/test/bouncybubbles/BouncyBubbles.java
[parsing    /data/data/com.calsignlabs.apde/app_build/src/processing/test/bouncybubbles/BouncyBubbles.java - #1/1]
[reading    processing/core/PApplet.class]
[reading    android/app/Activity.class]
[reading    android/view/ContextThemeWrapper.class]
[reading    android/content/ContextWrapper.class]
[reading    android/content/Context.class]
[reading    java/lang/Object.class]
[reading    android/content/ComponentCallbacks.class]
[reading    android/view/View$OnCreateContextMenuListener.class]
[reading    android/view/View.class]
[reading    android/view/KeyEvent$Callback.class]
[reading    android/view/KeyEvent.class]
[reading    android/os/Parcelable$Creator.class]
[reading    android/os/Parcelable.class]
[reading    android/view/Window$Callback.class]
[reading    android/view/Window.class]
[reading    android/view/LayoutInflater$Factory.class]
[reading    android/view/LayoutInflater.class]
[reading    java/lang/Runnable.class]
[reading    processing/core/PConstants.class]
[analyzing  /data/data/com.calsignlabs.apde/app_build/src/processing/test/bouncybubbles/BouncyBubbles.java - #1/1]
[reading    java/util/HashMap.class]
[reading    java/util/Map$Entry.class]
[reading    java/util/Map.class]
[reading    java/util/Map$Entry.class]
[reading    java/util/ArrayList.class]
[reading    java/io/File.class]
[reading    java/io/BufferedReader.class]
[reading    java/io/PrintWriter.class]
[reading    java/io/InputStream.class]
[reading    java/io/OutputStream.class]
[reading    java/io/IOException.class]
[reading    android/content/res/Configuration.class]
[reading    android/os/Bundle.class]
[reading    android/content/res/Resources$Theme.class]
[reading    android/content/res/Resources.class]
[reading    java/lang/String.class]
[reading    android/content/Intent.class]
[reading    android/content/IntentSender.class]
[reading    android/content/IntentSender$SendIntentException.class]
[reading    android/content/pm/PackageManager$NameNotFoundException.class]
[reading    android/content/pm/PackageManager.class]
[reading    android/net/Uri.class]
[reading    android/content/ComponentName.class]
[reading    android/content/ServiceConnection.class]
[reading    android/content/BroadcastReceiver.class]
[reading    android/os/Handler.class]
[reading    android/content/IntentFilter.class]
[reading    android/graphics/Bitmap.class]
[reading    android/graphics/drawable/Drawable.class]
[reading    android/database/sqlite/SQLiteDatabase.class]
[reading    android/database/sqlite/SQLiteDatabase$CursorFactory.class]
[reading    java/io/FileOutputStream.class]
[reading    java/io/FileNotFoundException.class]
[reading    java/io/FileInputStream.class]
[reading    android/content/SharedPreferences.class]
[reading    android/content/pm/ApplicationInfo.class]
[reading    java/lang/ClassLoader.class]
[reading    android/os/Looper.class]
[reading    android/content/ContentResolver.class]
[reading    android/content/res/AssetManager.class]
[reading    java/lang/System.class]
[reading    java/io/PrintStream.class]
[parsing    /data/data/com.calsignlabs.apde/app_build/src/processing/test/bouncybubbles/APDEInternalLogBroadcasterUtil.java - #2/2]
[reading    java/lang/Thread.class]
[reading    java/lang/Thread$UncaughtExceptionHandler.class]
[reading    java/io/Flushable.class]
[reading    java/io/Closeable.class]
[reading    java/io/UnsupportedEncodingException.class]
[analyzing  /data/data/com.calsignlabs.apde/app_build/src/processing/test/bouncybubbles/APDEInternalLogBroadcasterUtil.java - #2/2]
[writing    processing/test/bouncybubbles/BouncyBubbles.class - #1]
[writing    processing/test/bouncybubbles/BouncyBubbles$Ball.class - #2]
[reading    java/lang/Throwable.class]
[completed  /data/data/com.calsignlabs.apde/app_build/src/processing/test/bouncybubbles/BouncyBubbles.java - #1/2]
[reading    java/lang/Override.class]
[reading    java/lang/Class.class]
[writing    processing/test/bouncybubbles/APDEInternalLogBroadcasterUtil$1.class - #3]
[writing    processing/test/bouncybubbles/APDEInternalLogBroadcasterUtil.class - #4]
[writing    processing/test/bouncybubbles/APDEInternalLogBroadcasterUtil$APDEInternalExceptionHandler.class - #5]
[writing    processing/test/bouncybubbles/APDEInternalLogBroadcasterUtil$APDEInternalConsoleStream.class - #6]
[completed  /data/data/com.calsignlabs.apde/app_build/src/processing/test/bouncybubbles/APDEInternalLogBroadcasterUtil.java - #2/2]
[2 units compiled]
[6 .class files generated]
----------
1. WARNING in /data/data/com.calsignlabs.apde/app_build/src/processing/test/bouncybubbles/BouncyBubbles.java (at line 4)
	import processing.data.*; 
	       ^^^^^^^^^^^^^^^
The import processing.data is never used
----------
2. WARNING in /data/data/com.calsignlabs.apde/app_build/src/processing/test/bouncybubbles/BouncyBubbles.java (at line 5)
	import processing.event.*; 
	       ^^^^^^^^^^^^^^^^
The import processing.event is never used
----------
3. WARNING in /data/data/com.calsignlabs.apde/app_build/src/processing/test/bouncybubbles/BouncyBubbles.java (at line 6)
	import processing.opengl.*; 
	       ^^^^^^^^^^^^^^^^^
The import processing.opengl is never used
----------
4. WARNING in /data/data/com.calsignlabs.apde/app_build/src/processing/test/bouncybubbles/BouncyBubbles.java (at line 8)
	import java.util.HashMap; 
	       ^^^^^^^^^^^^^^^^^
The import java.util.HashMap is never used
----------
5. WARNING in /data/data/com.calsignlabs.apde/app_build/src/processing/test/bouncybubbles/BouncyBubbles.java (at line 9)
	import java.util.ArrayList; 
	       ^^^^^^^^^^^^^^^^^^^
The import java.util.ArrayList is never used
----------
6. WARNING in /data/data/com.calsignlabs.apde/app_build/src/processing/test/bouncybubbles/BouncyBubbles.java (at line 10)
	import java.io.File; 
	       ^^^^^^^^^^^^
The import java.io.File is never used
----------
7. WARNING in /data/data/com.calsignlabs.apde/app_build/src/processing/test/bouncybubbles/BouncyBubbles.java (at line 11)
	import java.io.BufferedReader; 
	       ^^^^^^^^^^^^^^^^^^^^^^
The import java.io.BufferedReader is never used
----------
8. WARNING in /data/data/com.calsignlabs.apde/app_build/src/processing/test/bouncybubbles/BouncyBubbles.java (at line 12)
	import java.io.PrintWriter; 
	       ^^^^^^^^^^^^^^^^^^^
The import java.io.PrintWriter is never used
----------
9. WARNING in /data/data/com.calsignlabs.apde/app_build/src/processing/test/bouncybubbles/BouncyBubbles.java (at line 13)
	import java.io.InputStream; 
	       ^^^^^^^^^^^^^^^^^^^
The import java.io.InputStream is never used
----------
10. WARNING in /data/data/com.calsignlabs.apde/app_build/src/processing/test/bouncybubbles/BouncyBubbles.java (at line 14)
	import java.io.OutputStream; 
	       ^^^^^^^^^^^^^^^^^^^^
The import java.io.OutputStream is never used
----------
11. WARNING in /data/data/com.calsignlabs.apde/app_build/src/processing/test/bouncybubbles/BouncyBubbles.java (at line 15)
	import java.io.IOException; 
	       ^^^^^^^^^^^^^^^^^^^
The import java.io.IOException is never used
----------
11 problems (11 warnings)
Dexing with DX Dexer...
processing /data/data/com.calsignlabs.apde/app_build/bin/classes/./processing/test/bouncybubbles/APDEInternalLogBroadcasterUtil.class...
processing /data/data/com.calsignlabs.apde/app_build/bin/classes/./processing/test/bouncybubbles/APDEInternalLogBroadcasterUtil$APDEInternalExceptionHandler.class...
processing /data/data/com.calsignlabs.apde/app_build/bin/classes/./processing/test/bouncybubbles/APDEInternalLogBroadcasterUtil$APDEInternalConsoleStream.class...
processing /data/data/com.calsignlabs.apde/app_build/bin/classes/./processing/test/bouncybubbles/APDEInternalLogBroadcasterUtil$1.class...
processing /data/data/com.calsignlabs.apde/app_build/bin/classes/./processing/test/bouncybubbles/BouncyBubbles$Ball.class...
processing /data/data/com.calsignlabs.apde/app_build/bin/classes/./processing/test/bouncybubbles/BouncyBubbles.class...
Merging DEX files with DX Merger...
DX Merger failed
java.nio.BufferOverflowException
	at java.nio.ByteArrayBuffer.putShort(ByteArrayBuffer.java:405)
	at com.android.dex.Dex$Section.writeShort(Dex.java:818)
	at com.android.dex.Dex$Section.writeTypeList(Dex.java:870)
	at com.android.dx.merge.DexMerger$3.write(DexMerger.java:437)
	at com.android.dx.merge.DexMerger$3.write(DexMerger.java:423)
	at com.android.dx.merge.DexMerger$IdMerger.mergeUnsorted(DexMerger.java:317)
	at com.android.dx.merge.DexMerger.mergeTypeLists(DexMerger.java:423)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:163)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:187)
	at com.android.dx.merge.DexMerger.main(DexMerger.java:1114)
	at com.calsignlabs.apde.build.Build.build(Build.java:898)
	at com.calsignlabs.apde.EditorActivity$22.run(EditorActivity.java:2295)
	at java.lang.Thread.run(Thread.java:841)

**Comment by JackWitherell** [comment]
Believe it or not, I'm having this same issue in 2016 on a Pixel C tablet with android 7.0

**Comment by Pablofero** [comment]
I have the same issue, too.Oneplus 3 with android 7.0

**Comment by Calsign** [comment]
@JackWitherell @Pablofero

This issue has been fixed in v0.4.0-pre2, available from the APDE Preview Channel. You can join the preview channel and the follow the instructions at the top to receive the update or wait until it rolls out to the primary channel:

https://plus.google.com/communities/117703520591262292626

This is a different issue from the original bug report here. The BufferOverflowException is a known issue for which I do not currently have a solution.
