### ISSUE TITLE
Ketai imports fail

### ISSUE THREAD

**Issue by cgiles** [Calsign/APDE#22]
Hi, I just started to use your app, and it is awesome. 

I wanted to import the library ketai, which simplifies the access to the devices captors and hardware, and it fails.  

Once selected, the screen turns black, and the app stops responding.  

It would be great to be able to use ketai, as it is quite powerful. 

Regards.

**Comment by dzaima** [comment]
I've been using ketai on APDE for a while. I was having problems with it a lot but figured out what to do.

Pretty sure what I did was download [ketai 9](https://github.com/ketai/ketai/blob/master/downloads/Ketai_v9/library/Ketai.jar), dexed it with the built-in DX dexed and put the JARs in /storage/extsdcard/android/data/com.calsignlabs.apde/files/sketchbook/libraries/Ketai/library and /library-dex respectively. Dunno if there was a better way.

**Comment by dzaima** [comment]
Now in v4.0 the above method fails with the error (it installs fine):

java.lang.VerifyError: ketai/ui/KetaiGesture$1
	at ketai.ui.KetaiGesture.<init>(KetaiGesture.java:59)	at processing.test.lessonhelper3k.lessonHelper3k.ketaiInit(lessonHelper3k.java:285)
	at processing.test.lessonhelper3k.lessonHelper3k.setup(lessonHelper3k.java:790)
	at processing.core.PApplet.handleDraw(Unknown Source)
	at processing.core.PGraphicsAndroid2D.requestDraw(Unknown Source)
	at processing.core.PApplet.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:841)
The app fails to build when using `KetaiKeyboard.show(this)` or hide/toggle because that takes an Activity not [programName]. All worked perfectly in v3.x.

Android 4.4.4, ketai 9&12 are same.
