### ISSUE TITLE
Unable to compile sketch

### ISSUE THREAD

**Issue by Golfand** [Calsign/APDE#56]
No longer able to compile a sketch.

Stack trace:
Initializing build sequence…
Deleted old build folder
Injected log broadcaster
Detected architecture arm64-v8a

Packaging resources with AAPT…
Compiling with ECJ…
engineVerify

Dexing with DX Dexer…
Uncaught translation error: com.androidjarjar.dex.util.ExceptionWithContext: com.androidjarjar.dx.cf.attrib.RawAttribute cannot be cast to com.androidjarjar.dx.cf.attrib.AttSignature
1 error; aborting
DX Dexer failed with error code: 1
Launching sketch preview…
java.io.FileNotFoundException: /data/user/0/com.calsignlabs.apde/app_build/bin/sketch-classes.dex (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at com.calsignlabs.apde.build.Build.copyFile(Build.java:2401)
	at com.calsignlabs.apde.build.Build.launchPreview(Build.java:1304)
	at com.calsignlabs.apde.build.Build.build(Build.java:1026)
	at com.calsignlabs.apde.EditorActivity$29.run(EditorActivity.java:2925)
	at java.lang.Thread.run(Thread.java:761)

**Comment by RaspyHarmony101** [comment]
Can you send your code so that I may try to run it?

**Comment by Golfand** [comment]
@RaspyHarmony101 

## Sketch:
```
void setup()
{
  fullScreen();
  frameRate(10);
}

void draw()
{
  background(0);
}
```

## Component:
```
class Component
{
  public int id;
  public String text;
  public float x, y;
  public String type = "None";
  
  public Component()
  {
    x = 0;
    y = 0;
    
    Components.add(this);
  }
  
  public void display()
  {
    println("a " + type + " is displayed");
  }
  
  public void update()
  {
    println("a " + type + " is updated");
  }
}
```

## Components:
```
static class Components
{
  public static int count = 0;
  static ArrayList<Component> list;
  
  public static Component[] get()
  {
    if (list == null)
      list = new ArrayList<Component>();
    
    return list.toArray(new Component[list.size()]);
  }
  
  public static void add(Component c)
  {
    if (list == null)
      list = new ArrayList<Component>();
  }
  
  public static void remove(Component c)
  {
    if (list == null)
      list = new ArrayList<Component>();
  }
}
```

**Comment by RaspyHarmony101** [comment]
I'm not having trouble running the sketch so maybe its your platform? Another note is that component class is not being used.

**Comment by RaspyHarmony101** [comment]
Glad its fixed. Be sure to close the issue!

**Comment by Golfand** [comment]
@RaspyHarmony101 
The issue is that APDE randomly deleted/corrupted one of its files.
I had to completely reinstall the app to get it to work.

**Comment by Calsign** [comment]
@Golfand 

This is a new one.

The strange thing is that the problem seems to be coming from dx, and APDE uses dx as a library. The library is loaded by ART, not by APDE itself. It seems that the installation of APDE itself was corrupted, i.e. the corruption wasn't APDE's fault. But I don't have much to work with here.

What circumstances led to this issue? Did APDE just get updated? Did this happen totally randomly? Or something else?

**Comment by Golfand** [comment]
@Calsign 
It happened randomly when running the sketch in preview mode

**Comment by Golfand** [comment]
It happened again..
This time I noticed something really weird, dx fails everytime with a couple of errors and every time I run the sketch, the amount of errors increases by 1.

For example after 5 times of running:
```
Dexing with DX Dexer…
Uncaught translation error: com.androidjarjar.dex.util.ExceptionWithContext: com.androidjarjar.dx.cf.attrib.RawAttribute cannot be cast to com.androidjarjar.dx.cf.attrib.AttSignature
Uncaught translation error: com.androidjarjar.dex.util.ExceptionWithContext: com.androidjarjar.dx.cf.attrib.RawAttribute cannot be cast to com.androidjarjar.dx.cf.attrib.AttSignature
Uncaught translation error: com.androidjarjar.dex.util.ExceptionWithContext: com.androidjarjar.dx.cf.attrib.RawAttribute cannot be cast to com.androidjarjar.dx.cf.attrib.AttSignature
Uncaught translation error: com.androidjarjar.dex.util.ExceptionWithContext: com.androidjarjar.dx.cf.attrib.RawAttribute cannot be cast to com.androidjarjar.dx.cf.attrib.AttSignature
Uncaught translation error: com.androidjarjar.dex.util.ExceptionWithContext: com.androidjarjar.dx.cf.attrib.RawAttribute cannot be cast to com.androidjarjar.dx.cf.attrib.AttSignature
5 errors; aborting
```

And then the next time I run it:
```
Dexing with DX Dexer…
Uncaught translation error: com.androidjarjar.dex.util.ExceptionWithContext: com.androidjarjar.dx.cf.attrib.RawAttribute cannot be cast to com.androidjarjar.dx.cf.attrib.AttSignature
Uncaught translation error: com.androidjarjar.dex.util.ExceptionWithContext: com.androidjarjar.dx.cf.attrib.RawAttribute cannot be cast to com.androidjarjar.dx.cf.attrib.AttSignature
Uncaught translation error: com.androidjarjar.dex.util.ExceptionWithContext: com.androidjarjar.dx.cf.attrib.RawAttribute cannot be cast to com.androidjarjar.dx.cf.attrib.AttSignature
Uncaught translation error: com.androidjarjar.dex.util.ExceptionWithContext: com.androidjarjar.dx.cf.attrib.RawAttribute cannot be cast to com.androidjarjar.dx.cf.attrib.AttSignature
Uncaught translation error: com.androidjarjar.dex.util.ExceptionWithContext: com.androidjarjar.dx.cf.attrib.RawAttribute cannot be cast to com.androidjarjar.dx.cf.attrib.AttSignature
Uncaught translation error: com.androidjarjar.dex.util.ExceptionWithContext: com.androidjarjar.dx.cf.attrib.RawAttribute cannot be cast to com.androidjarjar.dx.cf.attrib.AttSignature
6 errors; aborting
DX Dexer failed with error code: 1
```
