### ISSUE TITLE
Issue after renaming tab

### ISSUE THREAD

**Issue by 1icri** [Calsign/APDE#58]
*Note: I'm reporting this while I have a chance now, I will check the logs and add more info when I have a bit more time*

The best way to describe this issue right now is as a timeline:
0. Editing a sketch on external SD with 3 tabs with the following names: avr_emu, instructions, Phasor_FullEmu. The sketch was copied from Windows so contain a lot of CR LF line endings.
1. Renamed first tab from avr_emu to Jatme
2. Tab order did not reorganise to correct alphabetical order as expected.
3. On trying to switch to another tab, APDE crashed.
4. Reopening it showed in the console a message something like "No value for Jatme.pde". Tab order is still incorrect.
5. Attempt to switch tabs again several times and crashing with the same message each time.
6. Same crash again one more time, this time the file Jatme.pde was deleted from the device.

**Comment by 1icri** [comment]
Here's a section of logcat which may or may not be relevant but occurred at the right time:
```
11-10 16:46:09.614 29005 29005 E AndroidRuntime: FATAL EXCEPTION: main
11-10 16:46:09.614 29005 29005 E AndroidRuntime: Process: com.calsignlabs.apde, PID: 29005
11-10 16:46:09.614 29005 29005 E AndroidRuntime: java.lang.IndexOutOfBoundsException: setSpan (215 ... 215) ends beyond length 41
11-10 16:46:09.614 29005 29005 E AndroidRuntime: 	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1108)
11-10 16:46:09.614 29005 29005 E AndroidRuntime: 	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:680)
11-10 16:46:09.614 29005 29005 E AndroidRuntime: 	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:673)
11-10 16:46:09.614 29005 29005 E AndroidRuntime: 	at android.text.Selection.setSelection(Selection.java:76)
11-10 16:46:09.614 29005 29005 E AndroidRuntime: 	at android.widget.EditText.setSelection(EditText.java:97)
11-10 16:46:09.614 29005 29005 E AndroidRuntime: 	at com.calsignlabs.apde.SketchFile.updateEditor(SketchFile.java:573)
11-10 16:46:09.614 29005 29005 E AndroidRuntime: 	at com.calsignlabs.apde.CodeAreaFragment.onResume(CodeAreaFragment.java:129)
11-10 16:46:09.614 29005 29005 E AndroidRuntime: 	at android.support.v4.app.Fragment.performResume(Fragment.java:2308)
...
```

Unforunately it seems debugLog.txt hasn't captured anything in the last week or so.

**Comment by 1icri** [comment]
Having looked at that section of logcat properly, I now see that it was trying to set the text selection range from some tab (presumably the renamed avr_emu / Jatme one) instead inside the Phasor_FullEmu tab (I believe it was the first tab), which is 41 bytes/characters long. It seems the selection can do weird things when renaming. I can't reproduce this issue by trying to force that possible cause, so either I'm looking in the wrong place or this is another annoying intermittent issue.
