### ISSUE TITLE
Error when loading a specific sound file

### ISSUE THREAD

**Issue by MarquesAnderson** [Calsign/APDE#61]
First of all, thank you Calsign for the new update! I am greatly enjoying these new editions! A great New Year's gift.

I have been trying to upload a sound file and I've gotten the following errors whether the file was a mp3 or wav. Note its the same sound playing, just converted into different forms. So when it's mp3:

java.lang.ArrayIndexOutOfBoundsException: length=63; index=63
	at fr.delthas.javamp3.Decoder.samples_I(Decoder.java:1506)
	at fr.delthas.javamp3.Decoder.decodeFrame(Decoder.java:515)
	at fr.delthas.javamp3.Sound.decodeFullyInto(Sound.java:228)
	at processing.sound.SoundFile.<init>(Unknown Source)
	at processing.test.evo_genesis.Evo_genesis.draw(Evo_genesis.java:1536)
	at processing.core.PApplet.handleDraw(PApplet.java:1818)
	at processing.core.PSurfaceNone.callDraw(PSurfaceNone.java:471)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:503)

And with a WAV file...

java.lang.ArithmeticException: divide by zero
	at com.jsyn.util.soundfile.WAVEFileParser.parseFmtChunk(Unknown Source)
	at com.jsyn.util.soundfile.WAVEFileParser.handleChunk(Unknown Source)
	at com.jsyn.util.soundfile.IFFParser.parseChunk(Unknown Source)
	at com.jsyn.util.soundfile.IFFParser.parseForm(Unknown Source)
	at com.jsyn.util.soundfile.IFFParser.parseChunk(Unknown Source)
	at com.jsyn.util.soundfile.IFFParser.parseAfterHead(Unknown Source)
	at com.jsyn.util.soundfile.AudioFileParser.load(Unknown Source)
	at com.jsyn.util.soundfile.CustomSampleLoader.loadFloatSample(Unknown Source)
	at com.jsyn.util.SampleLoader.loadFloatSample(Unknown Source)
	at processing.sound.SoundFile.<init>(Unknown Source)
	at processing.test.evo_genesis.Evo_genesis.draw(Evo_genesis.java:1536)
	at processing.core.PApplet.handleDraw(PApplet.java:1818)
	at processing.core.PSurfaceNone.callDraw(PSurfaceNone.java:471)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:503)

How might I go about fixing this problem?

**Comment by RaspyHarmony101** [comment]
[errorsongs.zip](https://github.com/Calsign/APDE/files/2730849/errorsongs.zip)

Here are the files in a zip folder.

**Comment by Calsign** [comment]
This is almost certainly an issue with the [Processing sound library](https://github.com/processing/processing-sound). It has been 2.5 years, so if it still isn't resolved then feel free to follow up there. But this issue isn't in scope for APDE, so I'm closing.
