### ISSUE TITLE
Can't use external libs because dexpath is fucked

### ISSUE THREAD

**Issue by dolflou032** [Calsign/APDE#65]
Initializing build sequence…
Deleted old build folder
Injected log broadcaster
Detected architecture armeabi-v7a

Packaging resources with AAPT…
Compiling with ECJ…

Dexing with DX Dexer…
Merging DEX files with DX Merger…
Merged dex #1 (34 defs/99,5KiB)
Merged dex #2 (1410 defs/2340,8KiB)
Merged dex #3 (71 defs/232,3KiB)
Merged dex #4 (19 defs/81,5KiB)
Merged dex #5 (117 defs/128,2KiB)
Merged dex #6 (18 defs/32,3KiB)
Merged dex #7 (6 defs/10,8KiB)
Merged dex #8 (62 defs/116,7KiB)
Result is 1737 defs/3825,9KiB. Took 2,2s
Building APK file with APKBuilder…

Signing and Zipaligning with ZipSigner…
Installing APK file…

Failed to delete old APK file
java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/sound/sampled/AudioFileFormat$Type;
	at ddf.minim.Minim.<clinit>(Minim.java:94)
	at processing.test.drummachine.DrumMachine.setup(DrumMachine.java:127)
	at processing.core.PApplet.handleDraw(PApplet.java:1801)
	at processing.core.PSurfaceNone.callDraw(PSurfaceNone.java:471)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:503)
Caused by: java.lang.ClassNotFoundException: Didn't find class "javax.sound.sampled.AudioFileFormat$Type" on path: DexPathList[[zip file "/data/app/processing.test.drummachine-pDrxf70AqwAxhmnk4HZz-w==/base.apk"],nativeLibraryDirectories=[/data/app/processing.test.drummachine-pDrxf70AqwAxhmnk4HZz-w==/lib/arm, /system/lib, /system/vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 5 more

Here is the log of the errorr
Please fix this asap

**Comment by Calsign** [comment]
APDE doesn't support Minim, but it does support the new Processing sound library. See the [FAQ](https://github.com/Calsign/APDE/wiki#where-are-the-serial-network-video-or-sound-libraries) for more information.
